name: CowBot
author: JRoy
version: 1.2
api-version: 1.14
main: io.github.jroy.cowbot.CowBot
depend: [PluginLibrary, Tagger]
commands:
  communism:
    description: Communism Command
    usage: /communism
  chat:
    description: Chat Command
    usage: /chat
  joindate:
    description: Join Date Command
    usage: /joindate
  dirt:
    description: Dirt
    usage: /dirt
  spawn:
    description: Teleports to spawn
    usage: /spawn
  fetchbaltop:
    description: Fetches baltop
    usage: /fetchbaltop