name: CowBot
author: JRoy
version: 1.2
api-version: 1.14
main: io.github.jroy.cowbot.CowBot
depend: [Tagger]
commands:
  communism:
    description: Communism Command
    usage: /communism
  chat:
    description: Chat Command
    usage: /chat
  joindate:
    description: Join Date Command
    usage: /joindate
  dirt:
    description: Dirt
    usage: /dirt