name: CowBot
author: JRoy
version: 1.2
api-version: 1.14
main: io.github.jroy.cowbot.CowBot
commands:
  communism:
    description: Communism Command
    usage: /communism
  disguise:
    description: dfddd
    usage: /disguise
  chat:
    description: Chat Command
    usage: /chat
  joindate:
    description: Join Date Command
    usage: /joindate