name: CowBot
author: JRoy
version: 1.0
api-version: 1.14
main: io.github.jroy.cowbot.CowBot
commands:
  communism:
    description: Communism Command
    usage: /communism
  fuckbungee:
    description: eee
    usage: /fuckbungee